name: CMake

on:
  - pull_request
  - workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt install -y cppcheck python3-pip clang valgrind && pip install cpplint

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -DUSE_SANITIZERS=OFF

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -VV

      - name: Linters
        working-directory: ${{github.workspace}}
        run: ./linters/run.sh

      - name: Valgrind
        working-directory: ${{github.workspace}}/build
        run: |
          valgrind --tool=memcheck --leak-check=yes -s --log-fd=1 ./tests/test_matrix_dot > /tmp/valgrind_result \
          && cat /tmp/valgrind_result \
          && ! grep "LEAK SUMMARY" /tmp/valgrind_result \
          && grep "ERROR SUMMARY: 0 errors" /tmp/valgrind_result

  build-sanitizers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_SANITIZERS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Sanitize
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -VV
